name: Question
description: Have a question on how to use Adelie?
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Got a question on how to do something with Adelie?  
        Feel free to write to me!!
  - type: textarea
    id: question
    attributes:
      label: Question
      description: >
        Enter your question here. Please try to provide as much detail as possible.
    validations:
      required: true
