name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test

    strategy:
      fail-fast: false

      matrix:
        platform:
          - { target: x86_64-pc-windows-msvc, os: windows-latest }
          - { target: x86_64-unknown-linux-gnu, os: ubuntu-latest }

    runs-on: ${{ matrix.platform.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: cargo build

      - name: Run compiler tests
        run: cargo test

  adelietest:
    name: Adelie Test

    strategy:
      fail-fast: false

      matrix:
        platform:
          - { target: x86_64-pc-windows-msvc, os: windows-latest }
          - { target: x86_64-unknown-linux-gnu, os: ubuntu-latest }

    runs-on: ${{ matrix.platform.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: GabrielBB/xvfb-action@v1

      - name: Run adelie tests
        run: make test

  clippy:
    name: Clippy

    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: prepare
        run: rustup component add clippy

      - name: clippy
        run: cargo clippy
